### PR TITLE
WF Maps

### PR DESCRIPTION
**Pull request by wackmf**
I found old maps. Not sure if you wanted to include these in the project or create a separate wfut-maps project.

### CODE REVIEW

**Review by colkassad — COMMENTED** [review]
Thanks for the pull request. Why did you include 105/*.zip? Is it for posterity?

**Comment by jrwhetse** [comment]
Just for posterity and wasn't sure it included anything useful. I can
remove it and try again.

**Comment by wackmf** [comment]
Just for posterity and wasn't sure it included anything useful. I can
remove it and try again.

**Comment by colkassad** [comment]
No need, we can remove it later if needed.

**Pull request merged**
